//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeMessage
    {
        public string tblMessageID { get; set; }
        public long tblEmployeeID { get; set; }
        public bool IsRead { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblMessage tblMessage { get; set; }
    }
}
