//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMessageMedia
    {
        public long tblMessageMediaID { get; set; }
        public string tblMessageID { get; set; }
        public string Path { get; set; }
        public int tblMediaType { get; set; }
    
        public virtual tblMessage tblMessage { get; set; }
    }
}
